package generators;

import nodes.ASTNode;
import nodes.product.ProductNode;
import nodes.product.ProductManagerNode;
import java.util.List;

/**
 * CSSGenerator generates CSS code for the product management application
 * Provides modern, responsive design with RTL support
 */
public class CSSGenerator {
    private StringBuilder cssBuilder;
    private String indentation;
    private int indentLevel;

    public CSSGenerator() {
        this.cssBuilder = new StringBuilder();
        this.indentation = "  ";
        this.indentLevel = 0;
    }

    /**
     * Generate complete CSS stylesheet
     */
    public String generateCSS() {
        cssBuilder.setLength(0);
        indentLevel = 0;

        // CSS Reset and Base Styles
        generateCSSReset();

        // Variables and Custom Properties
        generateCSSVariables();

        // Global Styles
        generateGlobalStyles();

        // Layout Components
        generateLayoutStyles();

        // Navigation Styles
        generateNavigationStyles();

        // Form Styles
        generateFormStyles();

        // Product Card Styles
        generateProductCardStyles();

        // Enhanced Product Styles
        generateEnhancedProductStyles();

        // Button Styles
        generateButtonStyles();

        // Notification Styles
        generateNotificationStyles();

        // Responsive Design
        generateResponsiveStyles();

        // Utility Classes
        generateUtilityStyles();

        return cssBuilder.toString();
    }

    /**
     * Generate CSS Reset
     */
    private void generateCSSReset() {
        addLine("/* CSS Reset */");
        addLine("* {");
        indentLevel++;
        addLine("margin: 0;");
        addLine("padding: 0;");
        addLine("box-sizing: border-box;");
        indentLevel--;
        addLine("}");
        addLine("");
    }

    /**
     * Generate CSS Variables
     */
    private void generateCSSVariables() {
        addLine("/* CSS Variables */");
        addLine(":root {");
        indentLevel++;
        addLine("--primary-color: #2563eb;");
        addLine("--primary-hover: #1d4ed8;");
        addLine("--secondary-color: #64748b;");
        addLine("--success-color: #16a34a;");
        addLine("--warning-color: #ca8a04;");
        addLine("--danger-color: #dc2626;");
        addLine("--info-color: #0891b2;");
        addLine("--light-color: #f8fafc;");
        addLine("--dark-color: #1e293b;");
        addLine("--border-color: #e2e8f0;");
        addLine("--text-primary: #1e293b;");
        addLine("--text-secondary: #64748b;");
        addLine("--shadow-sm: 0 1px 2px 0 rgb(0 0 0 / 0.05);");
        addLine("--shadow-md: 0 4px 6px -1px rgb(0 0 0 / 0.1);");
        addLine("--shadow-lg: 0 10px 15px -3px rgb(0 0 0 / 0.1);");
        addLine("--border-radius: 8px;");
        addLine("--transition: all 0.3s ease;");
        indentLevel--;
        addLine("}");
        addLine("");
    }

    /**
     * Generate Global Styles
     */
    private void generateGlobalStyles() {
        addLine("/* Global Styles */");
        addLine("html {");
        indentLevel++;
        addLine("direction: rtl;");
        addLine("scroll-behavior: smooth;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine("body {");
        indentLevel++;
        addLine("font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;");
        addLine("line-height: 1.6;");
        addLine("color: var(--text-primary);");
        addLine("background-color: var(--light-color);");
        addLine("direction: rtl;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".container {");
        indentLevel++;
        addLine("max-width: 1200px;");
        addLine("margin: 0 auto;");
        addLine("padding: 0 20px;");
        indentLevel--;
        addLine("}");
        addLine("");
    }

    /**
     * Generate Layout Styles
     */
    private void generateLayoutStyles() {
        addLine("/* Layout Styles */");
        addLine(".header {");
        indentLevel++;
        addLine("background: linear-gradient(135deg, var(--primary-color), var(--primary-hover));");
        addLine("color: white;");
        addLine("box-shadow: var(--shadow-md);");
        addLine("position: sticky;");
        addLine("top: 0;");
        addLine("z-index: 1000;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".main-content {");
        indentLevel++;
        addLine("min-height: calc(100vh - 140px);");
        addLine("padding: 40px 0;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".section {");
        indentLevel++;
        addLine("margin-bottom: 60px;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".section-title {");
        indentLevel++;
        addLine("font-size: 2rem;");
        addLine("font-weight: 700;");
        addLine("color: var(--text-primary);");
        addLine("margin-bottom: 30px;");
        addLine("text-align: center;");
        addLine("display: flex;");
        addLine("align-items: center;");
        addLine("justify-content: center;");
        addLine("gap: 15px;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".footer {");
        indentLevel++;
        addLine("background-color: var(--dark-color);");
        addLine("color: white;");
        addLine("text-align: center;");
        addLine("padding: 20px 0;");
        addLine("margin-top: 40px;");
        indentLevel--;
        addLine("}");
        addLine("");
    }

    /**
     * Generate Navigation Styles
     */
    private void generateNavigationStyles() {
        addLine("/* Navigation Styles */");
        addLine(".navbar {");
        indentLevel++;
        addLine("display: flex;");
        addLine("justify-content: space-between;");
        addLine("align-items: center;");
        addLine("padding: 1rem 0;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".nav-brand {");
        indentLevel++;
        addLine("display: flex;");
        addLine("align-items: center;");
        addLine("gap: 10px;");
        addLine("font-size: 1.5rem;");
        addLine("font-weight: 700;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".nav-menu {");
        indentLevel++;
        addLine("display: flex;");
        addLine("list-style: none;");
        addLine("gap: 30px;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".nav-link {");
        indentLevel++;
        addLine("color: white;");
        addLine("text-decoration: none;");
        addLine("padding: 10px 15px;");
        addLine("border-radius: var(--border-radius);");
        addLine("transition: var(--transition);");
        addLine("display: flex;");
        addLine("align-items: center;");
        addLine("gap: 8px;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".nav-link:hover {");
        indentLevel++;
        addLine("background-color: rgba(255, 255, 255, 0.1);");
        addLine("transform: translateY(-2px);");
        indentLevel--;
        addLine("}");
        addLine("");
    }

    /**
     * Generate Form Styles
     */
    private void generateFormStyles() {
        addLine("/* Form Styles */");
        addLine(".product-form {");
        indentLevel++;
        addLine("max-width: 600px;");
        addLine("margin: 0 auto;");
        addLine("background: white;");
        addLine("padding: 30px;");
        addLine("border-radius: var(--border-radius);");
        addLine("box-shadow: var(--shadow-lg);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".form-group {");
        indentLevel++;
        addLine("margin-bottom: 20px;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".form-label {");
        indentLevel++;
        addLine("display: block;");
        addLine("margin-bottom: 8px;");
        addLine("font-weight: 600;");
        addLine("color: var(--text-primary);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".form-control {");
        indentLevel++;
        addLine("width: 100%;");
        addLine("padding: 12px 16px;");
        addLine("border: 2px solid var(--border-color);");
        addLine("border-radius: var(--border-radius);");
        addLine("font-size: 1rem;");
        addLine("transition: var(--transition);");
        addLine("direction: rtl;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".form-control:focus {");
        indentLevel++;
        addLine("outline: none;");
        addLine("border-color: var(--primary-color);");
        addLine("box-shadow: 0 0 0 3px rgba(37, 99, 235, 0.1);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine("textarea.form-control {");
        indentLevel++;
        addLine("min-height: 100px;");
        addLine("resize: vertical;");
        indentLevel--;
        addLine("}");
        addLine("");
    }

    /**
     * Generate Product Card Styles
     */
    private void generateProductCardStyles() {
        addLine("/* Product Card Styles */");
        addLine(".products-grid {");
        indentLevel++;
        addLine("display: grid;");
        addLine("grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));");
        addLine("gap: 30px;");
        addLine("margin-top: 30px;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".product-card {");
        indentLevel++;
        addLine("background: white;");
        addLine("border-radius: var(--border-radius);");
        addLine("box-shadow: var(--shadow-md);");
        addLine("overflow: hidden;");
        addLine("transition: var(--transition);");
        addLine("border: 1px solid var(--border-color);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".product-card:hover {");
        indentLevel++;
        addLine("transform: translateY(-5px);");
        addLine("box-shadow: var(--shadow-lg);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".product-image {");
        indentLevel++;
        addLine("height: 200px;");
        addLine("overflow: hidden;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".product-img {");
        indentLevel++;
        addLine("width: 100%;");
        addLine("height: 100%;");
        addLine("object-fit: cover;");
        addLine("transition: var(--transition);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".product-card:hover .product-img {");
        indentLevel++;
        addLine("transform: scale(1.05);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".product-info {");
        indentLevel++;
        addLine("padding: 20px;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".product-name {");
        indentLevel++;
        addLine("font-size: 1.25rem;");
        addLine("font-weight: 700;");
        addLine("color: var(--text-primary);");
        addLine("margin-bottom: 10px;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".product-description {");
        indentLevel++;
        addLine("color: var(--text-secondary);");
        addLine("margin-bottom: 15px;");
        addLine("line-height: 1.5;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".product-meta {");
        indentLevel++;
        addLine("display: flex;");
        addLine("justify-content: space-between;");
        addLine("align-items: center;");
        addLine("margin-bottom: 20px;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".product-price {");
        indentLevel++;
        addLine("font-size: 1.5rem;");
        addLine("font-weight: 700;");
        addLine("color: var(--success-color);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".product-category {");
        indentLevel++;
        addLine("background-color: var(--primary-color);");
        addLine("color: white;");
        addLine("padding: 4px 12px;");
        addLine("border-radius: 20px;");
        addLine("font-size: 0.875rem;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".product-actions {");
        indentLevel++;
        addLine("display: flex;");
        addLine("gap: 10px;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".no-products-message {");
        indentLevel++;
        addLine("text-align: center;");
        addLine("padding: 60px 20px;");
        addLine("color: var(--text-secondary);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".no-products-message i {");
        indentLevel++;
        addLine("font-size: 4rem;");
        addLine("margin-bottom: 20px;");
        addLine("color: var(--border-color);");
        indentLevel--;
        addLine("}");
        addLine("");
    }

    /**
     * Generate Button Styles
     */
    private void generateButtonStyles() {
        addLine("/* Button Styles */");
        addLine(".btn {");
        indentLevel++;
        addLine("display: inline-flex;");
        addLine("align-items: center;");
        addLine("gap: 8px;");
        addLine("padding: 10px 20px;");
        addLine("border: none;");
        addLine("border-radius: var(--border-radius);");
        addLine("font-size: 1rem;");
        addLine("font-weight: 600;");
        addLine("text-decoration: none;");
        addLine("cursor: pointer;");
        addLine("transition: var(--transition);");
        addLine("text-align: center;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".btn-primary {");
        indentLevel++;
        addLine("background-color: var(--primary-color);");
        addLine("color: white;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".btn-primary:hover {");
        indentLevel++;
        addLine("background-color: var(--primary-hover);");
        addLine("transform: translateY(-2px);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".btn-success {");
        indentLevel++;
        addLine("background-color: var(--success-color);");
        addLine("color: white;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".btn-warning {");
        indentLevel++;
        addLine("background-color: var(--warning-color);");
        addLine("color: white;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".btn-danger {");
        indentLevel++;
        addLine("background-color: var(--danger-color);");
        addLine("color: white;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".btn-info {");
        indentLevel++;
        addLine("background-color: var(--info-color);");
        addLine("color: white;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".btn-sm {");
        indentLevel++;
        addLine("padding: 6px 12px;");
        addLine("font-size: 0.875rem;");
        indentLevel--;
        addLine("}");
        addLine("");
    }

    /**
     * Generate Notification Styles
     */
    private void generateNotificationStyles() {
        addLine("/* Notification Styles */");
        addLine(".notification-container {");
        indentLevel++;
        addLine("position: fixed;");
        addLine("top: 20px;");
        addLine("right: 20px;");
        addLine("z-index: 10000;");
        addLine("max-width: 400px;");
        addLine("direction: rtl;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".notification {");
        indentLevel++;
        addLine("background: var(--primary-color);");
        addLine("color: white;");
        addLine("padding: 15px 20px;");
        addLine("margin-bottom: 10px;");
        addLine("border-radius: 8px;");
        addLine("box-shadow: 0 4px 12px rgba(0,0,0,0.15);");
        addLine("transform: translateX(100%);");
        addLine("transition: transform 0.3s ease;");
        addLine("display: flex;");
        addLine("align-items: center;");
        addLine("gap: 10px;");
        addLine("max-width: 100%;");
        addLine("position: relative;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".notification.show {");
        indentLevel++;
        addLine("transform: translateX(0);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".notification-success {");
        indentLevel++;
        addLine("background: var(--success-color);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".notification-error {");
        indentLevel++;
        addLine("background: var(--danger-color);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".notification-warning {");
        indentLevel++;
        addLine("background: var(--warning-color);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".notification-info {");
        indentLevel++;
        addLine("background: var(--info-color);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".notification i {");
        indentLevel++;
        addLine("font-size: 1.2rem;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".notification button {");
        indentLevel++;
        addLine("background: none;");
        addLine("border: none;");
        addLine("color: white;");
        addLine("font-size: 20px;");
        addLine("cursor: pointer;");
        addLine("padding: 0;");
        addLine("width: 24px;");
        addLine("height: 24px;");
        addLine("display: flex;");
        addLine("align-items: center;");
        addLine("justify-content: center;");
        addLine("position: absolute;");
        addLine("top: 5px;");
        addLine("right: 5px;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".notification button:hover {");
        indentLevel++;
        addLine("opacity: 0.8;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine("/* Image Preview Styles */");
        addLine(".image-preview-item {");
        indentLevel++;
        addLine("position: relative;");
        addLine("width: 100px;");
        addLine("height: 100px;");
        addLine("border-radius: 8px;");
        addLine("overflow: hidden;");
        addLine("border: 2px solid var(--border-color);");
        addLine("transition: var(--transition);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".image-preview-item:hover {");
        indentLevel++;
        addLine("border-color: var(--primary-color);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".image-preview-item img {");
        indentLevel++;
        addLine("width: 100%;");
        addLine("height: 100%;");
        addLine("object-fit: cover;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".image-preview-item button {");
        indentLevel++;
        addLine("position: absolute;");
        addLine("top: 5px;");
        addLine("right: 5px;");
        addLine("background: rgba(220, 38, 38, 0.9);");
        addLine("color: white;");
        addLine("border: none;");
        addLine("border-radius: 50%;");
        addLine("width: 20px;");
        addLine("height: 20px;");
        addLine("cursor: pointer;");
        addLine("font-size: 14px;");
        addLine("display: flex;");
        addLine("align-items: center;");
        addLine("justify-content: center;");
        addLine("transition: var(--transition);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".image-preview-item button:hover {");
        indentLevel++;
        addLine("background: rgba(220, 38, 38, 1);");
        addLine("transform: scale(1.1);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine("/* Loading States */");
        addLine(".loading {");
        indentLevel++;
        addLine("opacity: 0.6;");
        addLine("pointer-events: none;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".loading::after {");
        indentLevel++;
        addLine("content: '';");
        addLine("position: absolute;");
        addLine("top: 50%;");
        addLine("left: 50%;");
        addLine("width: 20px;");
        addLine("height: 20px;");
        addLine("margin: -10px 0 0 -10px;");
        addLine("border: 2px solid var(--primary-color);");
        addLine("border-top: 2px solid transparent;");
        addLine("border-radius: 50%;");
        addLine("animation: spin 1s linear infinite;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine("@keyframes spin {");
        indentLevel++;
        addLine("0% { transform: rotate(0deg); }");
        addLine("100% { transform: rotate(360deg); }");
        indentLevel--;
        addLine("}");
        addLine("");
    }

    /**
     * Generate Responsive Styles
     */
    private void generateResponsiveStyles() {
        addLine("/* Responsive Design */");
        addLine("@media (max-width: 768px) {");
        indentLevel++;
        addLine(".navbar {");
        indentLevel++;
        addLine("flex-direction: column;");
        addLine("gap: 20px;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".nav-menu {");
        indentLevel++;
        addLine("flex-direction: column;");
        addLine("gap: 15px;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".products-grid {");
        indentLevel++;
        addLine("grid-template-columns: 1fr;");
        addLine("gap: 20px;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".product-form {");
        indentLevel++;
        addLine("margin: 0 20px;");
        addLine("padding: 20px;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".section-title {");
        indentLevel++;
        addLine("font-size: 1.5rem;");
        indentLevel--;
        addLine("}");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine("@media (max-width: 480px) {");
        indentLevel++;
        addLine(".container {");
        indentLevel++;
        addLine("padding: 0 15px;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".product-actions {");
        indentLevel++;
        addLine("flex-direction: column;");
        indentLevel--;
        addLine("}");
        indentLevel--;
        addLine("}");
        addLine("");
    }

    /**
     * Generate Enhanced Product Styles
     */
    private void generateEnhancedProductStyles() {
        addLine("/* Enhanced Product Styles */");
        addLine(".form-container {");
        indentLevel++;
        addLine("background: white;");
        addLine("border-radius: 16px;");
        addLine("box-shadow: var(--shadow-lg);");
        addLine("padding: 2rem;");
        addLine("margin: 2rem 0;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".form-section {");
        indentLevel++;
        addLine("margin-bottom: 2rem;");
        addLine("padding-bottom: 2rem;");
        addLine("border-bottom: 1px solid var(--border-color);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".form-section:last-child {");
        indentLevel++;
        addLine("border-bottom: none;");
        addLine("margin-bottom: 0;");
        addLine("padding-bottom: 0;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".form-section-title {");
        indentLevel++;
        addLine("font-size: 1.25rem;");
        addLine("font-weight: 600;");
        addLine("color: var(--text-primary);");
        addLine("margin-bottom: 1.5rem;");
        addLine("display: flex;");
        addLine("align-items: center;");
        addLine("gap: 0.5rem;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".form-row {");
        indentLevel++;
        addLine("display: grid;");
        addLine("grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));");
        addLine("gap: 1.5rem;");
        addLine("margin-bottom: 1rem;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".form-col {");
        indentLevel++;
        addLine("display: flex;");
        addLine("flex-direction: column;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".form-actions {");
        indentLevel++;
        addLine("display: flex;");
        addLine("gap: 1rem;");
        addLine("justify-content: flex-end;");
        addLine("margin-top: 2rem;");
        addLine("padding-top: 2rem;");
        addLine("border-top: 1px solid var(--border-color);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".image-upload-container {");
        indentLevel++;
        addLine("margin-top: 1rem;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".image-upload-area {");
        indentLevel++;
        addLine("border: 2px dashed var(--border-color);");
        addLine("border-radius: 12px;");
        addLine("padding: 2rem;");
        addLine("text-align: center;");
        addLine("cursor: pointer;");
        addLine("transition: var(--transition);");
        addLine("position: relative;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".image-upload-area:hover {");
        indentLevel++;
        addLine("border-color: var(--primary-color);");
        addLine("background: var(--primary-light);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".image-upload-area i {");
        indentLevel++;
        addLine("font-size: 3rem;");
        addLine("color: var(--text-secondary);");
        addLine("margin-bottom: 1rem;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".image-input {");
        indentLevel++;
        addLine("position: absolute;");
        addLine("top: 0;");
        addLine("left: 0;");
        addLine("width: 100%;");
        addLine("height: 100%;");
        addLine("opacity: 0;");
        addLine("cursor: pointer;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".image-preview {");
        indentLevel++;
        addLine("display: grid;");
        addLine("grid-template-columns: repeat(auto-fill, minmax(100px, 1fr));");
        addLine("gap: 1rem;");
        addLine("margin-top: 1rem;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".products-controls {");
        indentLevel++;
        addLine("display: flex;");
        addLine("justify-content: space-between;");
        addLine("align-items: center;");
        addLine("margin-bottom: 2rem;");
        addLine("flex-wrap: wrap;");
        addLine("gap: 1rem;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".search-filter-container {");
        indentLevel++;
        addLine("display: flex;");
        addLine("gap: 1rem;");
        addLine("flex-wrap: wrap;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".search-box {");
        indentLevel++;
        addLine("position: relative;");
        addLine("min-width: 300px;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".search-input {");
        indentLevel++;
        addLine("width: 100%;");
        addLine("padding: 0.75rem 1rem 0.75rem 3rem;");
        addLine("border: 2px solid var(--border-color);");
        addLine("border-radius: 25px;");
        addLine("font-size: 1rem;");
        addLine("transition: var(--transition);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".search-input:focus {");
        indentLevel++;
        addLine("outline: none;");
        addLine("border-color: var(--primary-color);");
        addLine("box-shadow: 0 0 0 3px rgba(37, 99, 235, 0.1);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".search-icon {");
        indentLevel++;
        addLine("position: absolute;");
        addLine("left: 1rem;");
        addLine("top: 50%;");
        addLine("transform: translateY(-50%);");
        addLine("color: var(--text-secondary);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".filter-controls {");
        indentLevel++;
        addLine("display: flex;");
        addLine("gap: 0.5rem;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".filter-select {");
        indentLevel++;
        addLine("padding: 0.75rem 1rem;");
        addLine("border: 2px solid var(--border-color);");
        addLine("border-radius: 8px;");
        addLine("font-size: 0.9rem;");
        addLine("background: white;");
        addLine("min-width: 150px;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".view-controls {");
        indentLevel++;
        addLine("display: flex;");
        addLine("gap: 0.25rem;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".view-btn {");
        indentLevel++;
        addLine("padding: 0.5rem;");
        addLine("border: 2px solid var(--border-color);");
        addLine("background: white;");
        addLine("border-radius: 8px;");
        addLine("cursor: pointer;");
        addLine("transition: var(--transition);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".view-btn.active {");
        indentLevel++;
        addLine("background: var(--primary-color);");
        addLine("border-color: var(--primary-color);");
        addLine("color: white;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".products-list {");
        indentLevel++;
        addLine("display: none;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".pagination {");
        indentLevel++;
        addLine("display: flex;");
        addLine("justify-content: center;");
        addLine("align-items: center;");
        addLine("gap: 0.5rem;");
        addLine("margin-top: 2rem;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".pagination-btn {");
        indentLevel++;
        addLine("padding: 0.5rem 1rem;");
        addLine("border: 2px solid var(--border-color);");
        addLine("background: white;");
        addLine("border-radius: 8px;");
        addLine("cursor: pointer;");
        addLine("transition: var(--transition);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".pagination-btn:hover {");
        indentLevel++;
        addLine("background: var(--primary-color);");
        addLine("border-color: var(--primary-color);");
        addLine("color: white;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".page-numbers {");
        indentLevel++;
        addLine("display: flex;");
        addLine("gap: 0.25rem;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".page-number {");
        indentLevel++;
        addLine("padding: 0.5rem 0.75rem;");
        addLine("border: 2px solid var(--border-color);");
        addLine("background: white;");
        addLine("border-radius: 8px;");
        addLine("cursor: pointer;");
        addLine("transition: var(--transition);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".page-number.active {");
        indentLevel++;
        addLine("background: var(--primary-color);");
        addLine("border-color: var(--primary-color);");
        addLine("color: white;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine("/* Product Details Styles */");
        addLine(".product-details-content {");
        indentLevel++;
        addLine("min-height: 400px;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".product-details-placeholder {");
        indentLevel++;
        addLine("text-align: center;");
        addLine("padding: 4rem 2rem;");
        addLine("color: var(--text-secondary);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".product-details-placeholder i {");
        indentLevel++;
        addLine("font-size: 4rem;");
        addLine("margin-bottom: 1rem;");
        addLine("color: var(--border-color);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".product-details-template {");
        indentLevel++;
        addLine("display: none;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".product-details-header {");
        indentLevel++;
        addLine("margin-bottom: 2rem;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".product-breadcrumb {");
        indentLevel++;
        addLine("display: flex;");
        addLine("align-items: center;");
        addLine("gap: 0.5rem;");
        addLine("margin-bottom: 1rem;");
        addLine("font-size: 0.9rem;");
        addLine("color: var(--text-secondary);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".product-breadcrumb a {");
        indentLevel++;
        addLine("color: var(--primary-color);");
        addLine("text-decoration: none;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".product-title-section h1 {");
        indentLevel++;
        addLine("font-size: 2.5rem;");
        addLine("font-weight: 700;");
        addLine("color: var(--text-primary);");
        addLine("margin-bottom: 1rem;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".product-meta-info {");
        indentLevel++;
        addLine("display: flex;");
        addLine("gap: 1rem;");
        addLine("flex-wrap: wrap;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".product-category-badge {");
        indentLevel++;
        addLine("background: var(--primary-color);");
        addLine("color: white;");
        addLine("padding: 0.5rem 1rem;");
        addLine("border-radius: 20px;");
        addLine("font-size: 0.9rem;");
        addLine("font-weight: 600;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".product-brand, .product-model {");
        indentLevel++;
        addLine("color: var(--text-secondary);");
        addLine("font-size: 0.9rem;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".product-details-body {");
        indentLevel++;
        addLine("display: grid;");
        addLine("grid-template-columns: 1fr 1fr;");
        addLine("gap: 3rem;");
        addLine("margin-bottom: 3rem;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".product-images-section {");
        indentLevel++;
        addLine("position: relative;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".main-image-container {");
        indentLevel++;
        addLine("position: relative;");
        addLine("border-radius: 12px;");
        addLine("overflow: hidden;");
        addLine("margin-bottom: 1rem;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".main-product-image {");
        indentLevel++;
        addLine("width: 100%;");
        addLine("height: 400px;");
        addLine("object-fit: cover;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".image-overlay {");
        indentLevel++;
        addLine("position: absolute;");
        addLine("top: 1rem;");
        addLine("right: 1rem;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".zoom-btn {");
        indentLevel++;
        addLine("background: rgba(255, 255, 255, 0.9);");
        addLine("border: none;");
        addLine("border-radius: 50%;");
        addLine("width: 40px;");
        addLine("height: 40px;");
        addLine("cursor: pointer;");
        addLine("transition: var(--transition);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".zoom-btn:hover {");
        indentLevel++;
        addLine("background: white;");
        addLine("transform: scale(1.1);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".thumbnail-images {");
        indentLevel++;
        addLine("display: flex;");
        addLine("gap: 0.5rem;");
        addLine("flex-wrap: wrap;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".thumbnail-img {");
        indentLevel++;
        addLine("width: 80px;");
        addLine("height: 80px;");
        addLine("object-fit: cover;");
        addLine("border-radius: 8px;");
        addLine("cursor: pointer;");
        addLine("border: 2px solid transparent;");
        addLine("transition: var(--transition);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".thumbnail-img:hover, .thumbnail-img.active {");
        indentLevel++;
        addLine("border-color: var(--primary-color);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".product-info-section {");
        indentLevel++;
        addLine("display: flex;");
        addLine("flex-direction: column;");
        addLine("justify-content: space-between;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".product-price-section {");
        indentLevel++;
        addLine("margin-bottom: 2rem;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".current-price {");
        indentLevel++;
        addLine("display: flex;");
        addLine("align-items: center;");
        addLine("gap: 1rem;");
        addLine("margin-bottom: 1rem;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".price-label {");
        indentLevel++;
        addLine("font-size: 1.1rem;");
        addLine("color: var(--text-secondary);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".price-value {");
        indentLevel++;
        addLine("font-size: 2rem;");
        addLine("font-weight: 700;");
        addLine("color: var(--success-color);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".product-availability {");
        indentLevel++;
        addLine("display: flex;");
        addLine("align-items: center;");
        addLine("gap: 1rem;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".availability-label {");
        indentLevel++;
        addLine("font-size: 1.1rem;");
        addLine("color: var(--text-secondary);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".availability-status {");
        indentLevel++;
        addLine("font-weight: 600;");
        addLine("color: var(--success-color);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".product-actions {");
        indentLevel++;
        addLine("display: flex;");
        addLine("flex-direction: column;");
        addLine("gap: 1rem;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".btn-lg {");
        indentLevel++;
        addLine("padding: 1rem 2rem;");
        addLine("font-size: 1.1rem;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".btn-outline {");
        indentLevel++;
        addLine("background: transparent;");
        addLine("border: 2px solid var(--border-color);");
        addLine("color: var(--text-primary);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".btn-outline:hover {");
        indentLevel++;
        addLine("background: var(--border-color);");
        addLine("color: var(--text-primary);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine("/* Product Tabs Styles */");
        addLine(".product-tabs {");
        indentLevel++;
        addLine("margin-top: 3rem;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".tabs-header {");
        indentLevel++;
        addLine("display: flex;");
        addLine("gap: 0.5rem;");
        addLine("margin-bottom: 2rem;");
        addLine("border-bottom: 2px solid var(--border-color);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".tab-btn {");
        indentLevel++;
        addLine("padding: 1rem 2rem;");
        addLine("border: none;");
        addLine("background: transparent;");
        addLine("color: var(--text-secondary);");
        addLine("font-size: 1rem;");
        addLine("font-weight: 600;");
        addLine("cursor: pointer;");
        addLine("transition: var(--transition);");
        addLine("border-bottom: 3px solid transparent;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".tab-btn:hover {");
        indentLevel++;
        addLine("color: var(--primary-color);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".tab-btn.active {");
        indentLevel++;
        addLine("color: var(--primary-color);");
        addLine("border-bottom-color: var(--primary-color);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".tabs-content {");
        indentLevel++;
        addLine("min-height: 300px;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".tab-content {");
        indentLevel++;
        addLine("display: none;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".tab-content.active {");
        indentLevel++;
        addLine("display: block;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".description-content h3, .specifications-content h3, .reviews-content h3, .related-content h3 {");
        indentLevel++;
        addLine("font-size: 1.5rem;");
        addLine("font-weight: 600;");
        addLine("color: var(--text-primary);");
        addLine("margin-bottom: 1.5rem;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".product-features h4 {");
        indentLevel++;
        addLine("font-size: 1.2rem;");
        addLine("font-weight: 600;");
        addLine("color: var(--text-primary);");
        addLine("margin-bottom: 1rem;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".product-features ul {");
        indentLevel++;
        addLine("list-style: none;");
        addLine("padding: 0;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".product-features li {");
        indentLevel++;
        addLine("padding: 0.5rem 0;");
        addLine("border-bottom: 1px solid var(--border-color);");
        addLine("display: flex;");
        addLine("align-items: center;");
        addLine("gap: 0.5rem;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".product-features li:before {");
        indentLevel++;
        addLine("content: '✓';");
        addLine("color: var(--success-color);");
        addLine("font-weight: bold;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".specs-grid {");
        indentLevel++;
        addLine("display: grid;");
        addLine("grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));");
        addLine("gap: 1.5rem;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".spec-item {");
        indentLevel++;
        addLine("display: flex;");
        addLine("justify-content: space-between;");
        addLine("padding: 1rem;");
        addLine("background: var(--background-light);");
        addLine("border-radius: 8px;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".spec-label {");
        indentLevel++;
        addLine("font-weight: 600;");
        addLine("color: var(--text-primary);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".spec-value {");
        indentLevel++;
        addLine("color: var(--text-secondary);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".reviews-summary {");
        indentLevel++;
        addLine("margin-bottom: 2rem;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".rating-overview {");
        indentLevel++;
        addLine("display: flex;");
        addLine("align-items: center;");
        addLine("gap: 2rem;");
        addLine("margin-bottom: 2rem;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".average-rating {");
        indentLevel++;
        addLine("text-align: center;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".rating-number {");
        indentLevel++;
        addLine("font-size: 3rem;");
        addLine("font-weight: 700;");
        addLine("color: var(--warning-color);");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".rating-stars {");
        indentLevel++;
        addLine("font-size: 1.5rem;");
        addLine("color: var(--warning-color);");
        addLine("margin: 0.5rem 0;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".total-reviews {");
        indentLevel++;
        addLine("color: var(--text-secondary);");
        addLine("font-size: 1.1rem;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".reviews-list {");
        indentLevel++;
        addLine("max-height: 400px;");
        addLine("overflow-y: auto;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".related-products-grid {");
        indentLevel++;
        addLine("display: grid;");
        addLine("grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));");
        addLine("gap: 1.5rem;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine("@media (max-width: 768px) {");
        indentLevel++;
        addLine(".product-details-body {");
        indentLevel++;
        addLine("grid-template-columns: 1fr;");
        addLine("gap: 2rem;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".tabs-header {");
        indentLevel++;
        addLine("flex-wrap: wrap;");
        indentLevel--;
        addLine("}");
        addLine("");
        addLine(".tab-btn {");
        indentLevel++;
        addLine("padding: 0.75rem 1rem;");
        addLine("font-size: 0.9rem;");
        indentLevel--;
        addLine("}");
        indentLevel--;
        addLine("}");
    }

    /**
     * Generate Utility Styles
     */
    private void generateUtilityStyles() {
        addLine("/* Utility Classes */");
        addLine(".text-center { text-align: center; }");
        addLine(".text-right { text-align: right; }");
        addLine(".text-left { text-align: left; }");
        addLine("");
        addLine(".mb-1 { margin-bottom: 0.25rem; }");
        addLine(".mb-2 { margin-bottom: 0.5rem; }");
        addLine(".mb-3 { margin-bottom: 1rem; }");
        addLine(".mb-4 { margin-bottom: 1.5rem; }");
        addLine(".mb-b { margin-bottom: 3rem; }");
        addLine("");
        addLine(".mt-1 { margin-top: 0.25rem; }");
        addLine(".mt-2 { margin-top: 0.5rem; }");
        addLine(".mt-3 { margin-top: 1rem; }");
        addLine(".mt-4 { margin-top: 1.5rem; }");
        addLine(".mt-5 { margin-top: 3rem; }");
        addLine("");
        addLine(".d-none { display: none; }");
        addLine(".d-block { display: block; }");
        addLine(".d-flex { display: flex; }");
        addLine(".d-grid { display: grid; }");
        addLine("");
        addLine(".w-100 { width: 100%; }");
        addLine(".h-100 { height: 100%; }");
        addLine("");
        addLine(".rounded { border-radius: var(--border-radius); }");
        addLine(".shadow { box-shadow: var(--shadow-md); }");
        addLine(".shadow-sm { box-shadow: var(--shadow-sm); }");
        addLine(".shadow-lg { box-shadow: var(--shadow-lg); }");
    }

    /**
     * Add line with proper indentation
     */
    private void addLine(String line) {
        for (int i = 0; i < indentLevel; i++) {
            cssBuilder.append(indentation);
        }
        cssBuilder.append(line).append("\n");
    }

    /**
     * Reset generator for new generation
     */
    public void reset() {
        cssBuilder.setLength(0);
        indentLevel = 0;
    }

    /**
     * Get current CSS content
     */
    public String getCurrentCSS() {
        return cssBuilder.toString();
    }
}
