// Product Management Application - Generated by Angular Compiler
// State Management and CRUD Operations

(function() {
  'use strict';
  
  // State Management System
  class StateManager {
    constructor() {
      this.state = {
        // Product State
        products: [],
        currentProduct: null,
        selectedProductId: null,
        productFilters: {
          search: '',
          category: '',
          sortBy: 'newest',
          priceRange: { min: 0, max: Infinity }
        },
        // UI State
        ui: {
          currentView: 'grid',
          currentPage: 1,
          productsPerPage: 12,
          isLoading: false,
          activeTab: 'description',
          showAddForm: false,
          showEditForm: false
        },
        // Navigation State
        navigation: {
          currentSection: 'add-product',
          history: [],
          breadcrumbs: []
        },
        // Cart & Wishlist State
        cart: [],
        wishlist: [],
        // Notification State
        notifications: []
      };
      
      this.subscribers = new Map();
      this.stateId = 0;
    }
    
    // Subscribe to state changes
    subscribe(key, callback) {
      if (!this.subscribers.has(key)) {
        this.subscribers.set(key, new Set());
      }
      this.subscribers.get(key).add(callback);
      return () => this.subscribers.get(key).delete(callback);
    }
    
    // Notify subscribers of state changes
    notify(key, oldValue, newValue) {
      if (this.subscribers.has(key)) {
        this.subscribers.get(key).forEach(callback => {
          try {
            callback(oldValue, newValue, this.state);
          } catch (error) {
            console.error('Error in state subscriber:', error);
          }
        });
      }
    }
    
    // Update state with notification
    setState(updates) {
      const oldState = { ...this.state };
      
      Object.keys(updates).forEach(key => {
        if (this.state.hasOwnProperty(key)) {
          const oldValue = this.state[key];
          this.state[key] = { ...this.state[key], ...updates[key] };
          this.notify(key, oldValue, this.state[key]);
        }
      }
      
      this.stateId++;
      this.persistState();
    }
    
    // Get state value
    getState(key) {
      return key ? this.state[key] : this.state;
    }
    
    // Product State Management
    setProducts(products) {
      this.setState({ products });
    }
    
    addProduct(product) {
      const products = [...this.state.products, product];
      this.setState({ products });
      this.addNotification('?? ????? ?????? ?????', 'success');
    }
    
    updateProduct(productId, updates) {
      const products = this.state.products.map(p =>
        p.id === productId ? { ...p, ...updates, updatedAt: new Date().toISOString() } : p
      );
      this.setState({ products });
      this.addNotification('?? ????? ?????? ?????', 'success');
    }
    
    deleteProduct(productId) {
      const products = this.state.products.filter(p => p.id !== productId);
      this.setState({ products });
      this.addNotification('?? ??? ?????? ?????', 'success');
    }
    
    setCurrentProduct(product) {
      this.setState({ currentProduct: product, selectedProductId: product?.id });
    }
    
    // Filter State Management
    setFilter(key, value) {
      const productFilters = { ...this.state.productFilters, [key]: value };
      this.setState({ productFilters });
    }
    
    clearFilters() {
      this.setState({
        productFilters: {
          search: '',
          category: '',
          sortBy: 'newest',
          priceRange: { min: 0, max: Infinity }
        }
      });
    }
    
    // UI State Management
    setUIState(updates) {
      this.setState({ ui: { ...this.state.ui, ...updates } });
    }
    
    setCurrentView(view) {
      this.setUIState({ currentView: view });
    }
    
    setCurrentPage(page) {
      this.setUIState({ currentPage: page });
    }
    
    setActiveTab(tab) {
      this.setUIState({ activeTab: tab });
    }
    
    // Navigation State Management
    navigateTo(section, data = {}) {
      const navigation = {
        currentSection: section,
        history: [...this.state.navigation.history, this.state.navigation.currentSection],
        breadcrumbs: this.generateBreadcrumbs(section, data)
      };
      
      this.setState({ navigation });
      this.updateURL(section);
    }
    
    goBack() {
      if (this.state.navigation.history.length > 0) {
        const previousSection = this.state.navigation.history.pop();
        const navigation = {
          currentSection: previousSection,
          history: this.state.navigation.history,
          breadcrumbs: this.generateBreadcrumbs(previousSection)
        };
        
        this.setState({ navigation });
        this.updateURL(previousSection);
      }
    }
    
    generateBreadcrumbs(section, data = {}) {
      const breadcrumbs = [
        { name: '????????', section: 'add-product' }
      ];
      
      switch (section) {
        case 'products':
          breadcrumbs.push({ name: '????????', section: 'products' });
        break;
        case 'product-details':
          breadcrumbs.push({ name: '????????', section: 'products' });
          if (data.productName) {
            breadcrumbs.push({ name: data.productName, section: 'product-details' });
          }
        break;
      }
      
      return breadcrumbs;
    }
    
    updateURL(section) {
      const url = new URL(window.location);
      url.hash = section;
      window.history.pushState({}, '', url);
    }
    
    // Cart State Management
    addToCart(product, quantity = 1) {
      const existingItem = this.state.cart.find(item => item.id === product.id);
      
      if (existingItem) {
        existingItem.quantity += quantity;
        this.setState({ cart: [...this.state.cart] });
      } else {
        const cart = [...this.state.cart, { ...product, quantity }];
        this.setState({ cart });
      }
      
      this.addNotification(`?? ????? ${product.name} ??? ?????`, 'success');
    }
    
    removeFromCart(productId) {
      const cart = this.state.cart.filter(item => item.id !== productId);
      this.setState({ cart });
    }
    
    updateCartQuantity(productId, quantity) {
      if (quantity <= 0) {
        this.removeFromCart(productId);
      } else {
        const cart = this.state.cart.map(item =>
          item.id === productId ? { ...item, quantity } : item
        );
        this.setState({ cart });
      }
    }
    
    // Wishlist State Management
    addToWishlist(product) {
      if (!this.state.wishlist.find(item => item.id === product.id)) {
        const wishlist = [...this.state.wishlist, product];
        this.setState({ wishlist });
        this.addNotification(`?? ????? ${product.name} ??? ???????`, 'success');
      }
    }
    
    removeFromWishlist(productId) {
      const wishlist = this.state.wishlist.filter(item => item.id !== productId);
      this.setState({ wishlist });
    }
    
    // Notification State Management
    addNotification(message, type = 'info', duration = 5000) {
      const notification = {
        id: Date.now(),
        message,
        type,
        timestamp: new Date().toISOString()
      };
      
      const notifications = [...this.state.notifications, notification];
      this.setState({ notifications });
      
      // Auto-remove notification after duration
      setTimeout(() => {
        this.removeNotification(notification.id);
      }, duration);
    }
    
    removeNotification(id) {
      const notifications = this.state.notifications.filter(n => n.id !== id);
      this.setState({ notifications });
    }
    
    // State Persistence
    persistState() {
      try {
        const stateToPersist = {
          products: this.state.products,
          cart: this.state.cart,
          wishlist: this.state.wishlist,
          productFilters: this.state.productFilters
        };
        localStorage.setItem('productManagerState', JSON.stringify(stateToPersist));
      } catch (error) {
        console.error('Error persisting state:', error);
      }
    }
    
    loadPersistedState() {
      try {
        const persisted = localStorage.getItem('productManagerState');
        if (persisted) {
          const parsed = JSON.parse(persisted);
          this.setState({
            products: parsed.products || [],
            cart: parsed.cart || [],
            wishlist: parsed.wishlist || [],
            productFilters: parsed.productFilters || this.state.productFilters
          });
        }
      } catch (error) {
        console.error('Error loading persisted state:', error);
      }
    }
    
    // Get computed state
    getFilteredProducts() {
      let products = [...this.state.products];
      
      // Apply search filter
      if (this.state.productFilters.search) {
        const searchTerm = this.state.productFilters.search.toLowerCase();
        products = products.filter(product =>
          product.name.toLowerCase().includes(searchTerm) ||
          product.description.toLowerCase().includes(searchTerm) ||
          product.category.toLowerCase().includes(searchTerm)
        );
      }
      
      // Apply category filter
      if (this.state.productFilters.category) {
        products = products.filter(product => product.category === this.state.productFilters.category);
        }
        
        // Apply price filter
        products = products.filter(product =>
          product.price >= this.state.productFilters.priceRange.min &&
          product.price <= this.state.productFilters.priceRange.max
        );
        
        // Apply sorting
        switch (this.state.productFilters.sortBy) {
          case 'newest':
            products.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));
          break;
          case 'oldest':
            products.sort((a, b) => new Date(a.createdAt) - new Date(b.createdAt));
          break;
          case 'price-low':
            products.sort((a, b) => a.price - b.price);
          break;
          case 'price-high':
            products.sort((a, b) => b.price - a.price);
          break;
          case 'name-az':
            products.sort((a, b) => a.name.localeCompare(b.name, 'ar'));
          break;
          case 'name-za':
            products.sort((a, b) => b.name.localeCompare(a.name, 'ar'));
          break;
        }
        
        return products;
      }
      
      getPaginatedProducts() {
        const filtered = this.getFilteredProducts();
        const startIndex = (this.state.ui.currentPage - 1) * this.state.ui.productsPerPage;
        const endIndex = startIndex + this.state.ui.productsPerPage;
        return filtered.slice(startIndex, endIndex);
      }
      
      getCartTotal() {
        return this.state.cart.reduce((total, item) => total + (item.price * item.quantity), 0);
      }
      
      getCartItemCount() {
        return this.state.cart.reduce((count, item) => count + item.quantity, 0);
      }
    }
    
    // Create global state manager instance
    const stateManager = new StateManager();
    
    // Product Manager Class
    class ProductManager {
      constructor() {
        this.products = [];
        this.currentProduct = null;
        this.nextId = 1;
      }
      
      // Add new product
      addProduct(productData) {
        const product = {
          id: this.generateId(),
          ...productData,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString()
        };
        
        this.products.push(product);
        stateManager.setState({ products: [...this.products] });
        this.saveToLocalStorage();
        return product;
      }
      
      // Get product by ID
      getProduct(id) {
        return this.products.find(p => p.id === id);
      }
      
      // Update product
      updateProduct(id, updates) {
        const index = this.products.findIndex(p => p.id === id);
        if (index !== -1) {
          this.products[index] = {
            ...this.products[index],
            ...updates,
            updatedAt: new Date().toISOString()
          };
          stateManager.setState({ products: [...this.products] });
          this.saveToLocalStorage();
          return this.products[index];
        }
        return null;
      }
      
      // Delete product
      deleteProduct(id) {
        const index = this.products.findIndex(p => p.id === id);
        if (index !== -1) {
          this.products.splice(index, 1);
          stateManager.setState({ products: [...this.products] });
          this.saveToLocalStorage();
          return true;
        }
        return false;
      }
      
      // Get all products
      getAllProducts() {
        return [...this.products];
      }
      
      // Get products by category
      getProductsByCategory(category) {
        return this.products.filter(p => p.category === category);
      }
      
      // Search products
      searchProducts(query) {
        const lowerQuery = query.toLowerCase();
        return this.products.filter(p =>
          p.name.toLowerCase().includes(lowerQuery) ||
          p.description.toLowerCase().includes(lowerQuery) ||
          p.category.toLowerCase().includes(lowerQuery)
        );
      }
      
      // Generate unique ID
      generateId() {
        return this.nextId++;
      }
      
      // Save to localStorage
      saveToLocalStorage() {
        try {
          localStorage.setItem('products', JSON.stringify(this.products));
          localStorage.setItem('nextId', this.nextId.toString());
        } catch (error) {
          console.error('Error saving to localStorage:', error);
        }
      }
      
      // Load from localStorage
      loadFromLocalStorage() {
        try {
          const savedProducts = localStorage.getItem('products');
          const savedNextId = localStorage.getItem('nextId');
          
          if (savedProducts) {
            this.products = JSON.parse(savedProducts);
          }
          
          if (savedNextId) {
            this.nextId = parseInt(savedNextId);
          }
        } catch (error) {
          console.error('Error loading from localStorage:', error);
        }
      }
    }
    
    // Create global product manager instance
    const productManager = new ProductManager();
    
    // CRUD Operations
    const ProductOperations = {
      // Create - Add new product
      create: (productData) => {
        stateManager.setState({ loading: true, error: null });
        
        try {
          const product = productManager.addProduct(productData);
          stateManager.setState({ loading: false });
          showNotification('?? ????? ?????? ?????', 'success');
          return product;
        } catch (error) {
          stateManager.setState({ loading: false, error: error.message });
          showNotification('??? ?? ????? ??????', 'error');
          throw error;
        }
      },
      
      // Read - Get products
      read: (id = null) => {
        if (id) {
          return productManager.getProduct(id);
        }
        return productManager.getAllProducts();
      },
      
      // Update - Modify product
      update: (id, updates) => {
        stateManager.setState({ loading: true, error: null });
        
        try {
          const product = productManager.updateProduct(id, updates);
          if (product) {
            stateManager.setState({ loading: false });
            showNotification('?? ????? ?????? ?????', 'success');
            return product;
          } else {
            throw new Error('?????? ??? ?????');
          }
        } catch (error) {
          stateManager.setState({ loading: false, error: error.message });
          showNotification('??? ?? ????? ??????', 'error');
          throw error;
        }
      },
      
      // Delete - Remove product
      delete: (id) => {
        stateManager.setState({ loading: true, error: null });
        
        try {
          const success = productManager.deleteProduct(id);
          if (success) {
            stateManager.setState({ loading: false });
            showNotification('?? ??? ?????? ?????', 'success');
            return true;
          } else {
            throw new Error('?????? ??? ?????');
          }
        } catch (error) {
          stateManager.setState({ loading: false, error: error.message });
          showNotification('??? ?? ??? ??????', 'error');
        }
      }
    };
    
    // UI Event Handlers
    const EventHandlers = {
      // Handle form submission
      handleAddProduct: (event) => {
        event.preventDefault();
        
        const formData = new FormData(event.target);
        const productData = {
          name: formData.get('productName'),
          description: formData.get('productDescription'),
          price: parseFloat(formData.get('productPrice')),
          category: formData.get('productCategory'),
          imageUrl: formData.get('productImage') || 'placeholder.jpg'
        };
        
        try {
          ProductOperations.create(productData);
          event.target.reset();
          scrollToSection('products');
        } catch (error) {
          console.error('Error adding product:', error);
        }
      },
      
      // Handle product deletion
      handleDeleteProduct: (id) => {
        if (confirm('?? ??? ????? ?? ??? ??? ???????')) {
          try {
            ProductOperations.delete(id);
          } catch (error) {
            console.error('Error deleting product:', error);
          }
        }
      },
      
      // Handle product editing
      handleEditProduct: (id) => {
        const product = productManager.getProduct(id);
        if (product) {
          // Populate form with product data
          document.getElementById('productName').value = product.name;
          document.getElementById('productDescription').value = product.description;
          document.getElementById('productPrice').value = product.price;
          document.getElementById('productCategory').value = product.category;
          document.getElementById('productImage').value = product.imageUrl;
          
          // Change form to edit mode
          const form = document.getElementById('addProductForm');
          form.dataset.editMode = 'true';
          form.dataset.editId = id;
          
          // Update submit button
          const submitBtn = form.querySelector('button[type="submit"]');
          submitBtn.innerHTML = '<i class="fas fa-save"></i> ????? ??????';
          
          scrollToSection('add-product');
        }
      },
      
      // Handle product view
      handleViewProduct: (id) => {
        const product = productManager.getProduct(id);
        if (product) {
          displayProductDetails(product);
          scrollToSection('product-details');
        }
      }
    };
    
    // Utility Functions
    const Utils = {
      // Scroll to section
      scrollToSection: (sectionId) => {
        const section = document.getElementById(sectionId);
        if (section) {
          section.scrollIntoView({ behavior: 'smooth' });
        }
      },
      
      // Show notification
      showNotification: (message, type = 'info') => {
        const notification = document.createElement('div');
        notification.className = `notification notification-${type}`;
        notification.textContent = message;
        
        document.body.appendChild(notification);
        
        // Auto remove after 3 seconds
        setTimeout(() => {
          notification.remove();
        }, 3000);
      },
      
      // Format price
      formatPrice: (price) => {
        return new Intl.NumberFormat('ar-SA', {
          style: 'currency',
          currency: 'SAR'
        }).format(price);
      },
      
      // Format date
      formatDate: (dateString) => {
        return new Date(dateString).toLocaleDateString('ar-SA');
      }
    };
    
    // Initialize application when DOM is ready
    document.addEventListener('DOMContentLoaded', () => {
      // Load saved products
      productManager.loadFromLocalStorage();
      
      // Set up event listeners
      setupEventListeners();
      
      // Initial render
      renderProducts();
      
      // Subscribe to state changes
      stateManager.subscribe((state) => {
        renderProducts();
      });
    });
    
    // Setup event listeners
    function setupEventListeners() {
      // Add product form
      const addProductForm = document.getElementById('addProductForm');
      if (addProductForm) {
        addProductForm.addEventListener('submit', EventHandlers.handleAddProduct);
      }
      
      // Navigation links
      document.querySelectorAll('.nav-link').forEach(link => {
        link.addEventListener('click', (e) => {
          e.preventDefault();
          const targetId = link.getAttribute('href').substring(1);
          Utils.scrollToSection(targetId);
        });
      });
    }
    
    // Render products in the grid
    function renderProducts() {
      const productsGrid = document.getElementById('productsGrid');
      const noProductsMessage = document.getElementById('noProductsMessage');
      const products = productManager.getAllProducts();
      
      if (products.length === 0) {
        if (productsGrid) productsGrid.style.display = 'none';
        if (noProductsMessage) noProductsMessage.style.display = 'block';
      } else {
        if (productsGrid) productsGrid.style.display = 'grid';
        if (noProductsMessage) noProductsMessage.style.display = 'none';
        
        renderProductCards(products);
      }
    }
    
    // Render product cards
    function renderProductCards(products) {
      const productsGrid = document.getElementById('productsGrid');
      if (!productsGrid) return;
      
      // Clear existing cards (except sample card)
      const existingCards = productsGrid.querySelectorAll('.product-card:not(.sample-card)');
      existingCards.forEach(card => card.remove());
      
      // Add product cards
      products.forEach(product => {
        const card = createProductCard(product);
        productsGrid.appendChild(card);
      });
    }
    
    // Create product card element
    function createProductCard(product) {
      const card = document.createElement('div');
      card.className = 'product-card';
      card.innerHTML = `
        <div class="product-image">
        <img src="${product.imageUrl || 'placeholder.jpg'}" alt="${product.name}" class="product-img">
        </div>
        <div class="product-info">
        <h3 class="product-name">${product.name}</h3>
        <p class="product-description">${product.description}</p>
        <div class="product-meta">
        <span class="product-price">${Utils.formatPrice(product.price)}</span>
        <span class="product-category">${product.category}</span>
        </div>
        <div class="product-actions">
        <button class="btn btn-info btn-sm" onclick="EventHandlers.handleViewProduct('${product.id}')">
        <i class="fas fa-eye"></i> show
        </button>
        <button class="btn btn-warning btn-sm" onclick="EventHandlers.handleEditProduct('${product.id}')">
        <i class="fas fa-edit"></i> edit
        </button>
        <button class="btn btn-danger btn-sm" onclick="EventHandlers.handleDeleteProduct('${product.id}')">
        <i class="fas fa-trash"></i> delete
        </button>
        </div>
        </div>
        `;
        
        return card;
      }
      
      // Display product details
      function displayProductDetails(product) {
        const detailsContent = document.getElementById('productDetailsContent');
        if (!detailsContent) return;
        
        // Hide placeholder and show template
        const placeholder = detailsContent.querySelector('.product-details-placeholder');
        const template = detailsContent.querySelector('.product-details-template');
        if (placeholder) placeholder.style.display = 'none';
        if (template) template.style.display = 'block';
        
        // Populate product details
        populateProductDetails(product);
      }
      
      // Populate product details in template
      function populateProductDetails(product) {
        // Basic info
        const title = document.getElementById('productDetailTitle');
        const breadcrumbName = document.getElementById('productBreadcrumbName');
        const category = document.getElementById('productDetailCategory');
        const brand = document.getElementById('productDetailBrand');
        const model = document.getElementById('productDetailModel');
        const price = document.getElementById('productDetailPrice');
        const stock = document.getElementById('productDetailStock');
        const description = document.getElementById('productDetailDescription');
        
        if (title) title.textContent = product.name;
        if (breadcrumbName) breadcrumbName.textContent = product.name;
        if (category) category.textContent = product.category || '??? ????';
        if (brand) brand.textContent = product.brand || '??? ????';
        if (model) model.textContent = product.model || '??? ????';
        if (price) price.textContent = Utils.formatPrice(product.price);
        if (stock) {
          stock.textContent = product.inStock ? '?????' : '??? ?????';
          stock.className = product.inStock ? 'availability-status' : 'availability-status out-of-stock';
        }
        if (description) description.textContent = product.description || '?? ???? ???';
        
        // Images
        const mainImage = document.getElementById('productMainImage');
        const thumbnailContainer = document.getElementById('thumbnailImages');
        
        if (mainImage) {
          mainImage.src = product.imageUrl || 'placeholder.jpg';
          mainImage.alt = product.name;
        }
        
        if (thumbnailContainer) {
          thumbnailContainer.innerHTML = '';
          if (product.imageUrl) {
            const thumbnail = document.createElement('img');
            thumbnail.src = product.imageUrl;
            thumbnail.alt = product.name;
            thumbnail.className = 'thumbnail-img active';
            thumbnail.onclick = () => setMainImage(product.imageUrl);
            thumbnailContainer.appendChild(thumbnail);
          }
        }
        
        // Features
        populateProductFeatures(product.features || []);
        
        // Specifications
        populateProductSpecifications(product);
        
        // Reviews
        populateProductReviews(product.reviews || []);
        
        // Related products
        populateRelatedProducts(product.category);
      }
      
      // Set main image from thumbnail
      function setMainImage(imageUrl) {
        const mainImage = document.getElementById('productMainImage');
        if (mainImage) mainImage.src = imageUrl;
        
        // Update active thumbnail
        const thumbnails = document.querySelectorAll('.thumbnail-img');
        thumbnails.forEach(thumb => thumb.classList.remove('active'));
        event.target.classList.add('active');
      }
      
      // Populate product features
      function populateProductFeatures(features) {
        const featuresList = document.getElementById('featuresList');
        if (!featuresList) return;
        
        featuresList.innerHTML = '';
        if (features.length === 0) {
          featuresList.innerHTML = '<li>?? ???? ?????? ?????</li>';
        } else {
          features.forEach(feature => {
            const li = document.createElement('li');
            li.textContent = feature;
            featuresList.appendChild(li);
          });
        }
      }
      
      // Populate product specifications
      function populateProductSpecifications(product) {
        const specsGrid = document.getElementById('specsGrid');
        if (!specsGrid) return;
        
        specsGrid.innerHTML = '';
        
        const specs = [
          { label: '?????', value: product.name },
          { label: '?????', value: product.category || '??? ????' },
          { label: '??????? ????????', value: product.brand || '??? ????' },
          { label: '???????', value: product.model || '??? ????' },
          { label: '?????', value: product.weight ? `${product.weight} ???` : '??? ????' },
          { label: '???????', value: product.dimensions || '??? ????' },
          { label: '?????', value: Utils.formatPrice(product.price) },
          { label: '??????', value: product.inStock ? '?????' : '??? ?????' },
          { label: '????? ???????', value: Utils.formatDate(product.createdAt) },
          { label: '??? ?????', value: Utils.formatDate(product.updatedAt) }
        ];
        
        specs.forEach(spec => {
          const specItem = document.createElement('div');
          specItem.className = 'spec-item';
          specItem.innerHTML = `
            <span class="spec-label">${spec.label}:</span>
            <span class="spec-value">${spec.value}</span>
          `;
          specsGrid.appendChild(specItem);
        });
      }
      
      // Populate product reviews
      function populateProductReviews(reviews) {
        const averageRating = document.getElementById('averageRating');
        const ratingStars = document.getElementById('ratingStars');
        const totalReviews = document.getElementById('totalReviews');
        const reviewsList = document.getElementById('reviewsList');
        
        if (averageRating) {
          const avgRating = reviews.length > 0 ? (reviews.reduce((sum, r) => sum + r.rating, 0) / reviews.length).toFixed(1) : '0.0';
          averageRating.textContent = avgRating;
        }
        
        if (ratingStars) {
          const stars = '?'.repeat(Math.floor(avgRating)) + '?'.repeat(5 - Math.floor(avgRating));
          ratingStars.textContent = stars;
        }
        
        if (totalReviews) {
          totalReviews.textContent = `${reviews.length} ?????`;
        }
        
        if (reviewsList) {
          reviewsList.innerHTML = '';
          if (reviews.length === 0) {
            reviewsList.innerHTML = '<p>?? ???? ??????? ???</p>';
          } else {
            reviews.forEach(review => {
              const reviewItem = document.createElement('div');
              reviewItem.className = 'review-item';
              reviewItem.innerHTML = `
                <div class="review-header">
                <span class="review-author">${review.author}</span>
                <span class="review-rating">${'?'.repeat(review.rating)}</span>
                </div>
                <p class="review-text">${review.text}</p>
                <span class="review-date">${Utils.formatDate(review.date)}</span>
              `;
              reviewsList.appendChild(reviewItem);
            });
          }
        }
      }
      
      // Populate related products
      function populateRelatedProducts(category) {
        const relatedGrid = document.getElementById('relatedProductsGrid');
        if (!relatedGrid) return;
        
        relatedGrid.innerHTML = '';
        
        const relatedProducts = productManager.getAllProducts().filter(p => p.category === category && p.id !== currentProductId);
        const displayProducts = relatedProducts.slice(0, 6);
        
        if (displayProducts.length === 0) {
          relatedGrid.innerHTML = '<p>?? ???? ?????? ??? ???</p>';
        } else {
          displayProducts.forEach(product => {
            const productCard = createProductCard(product);
            relatedGrid.appendChild(productCard);
          });
        }
      }
      
      // Tab management functions
      function switchTab(tabName) {
        // Hide all tab contents
        const tabContents = document.querySelectorAll('.tab-content');
        tabContents.forEach(content => content.classList.remove('active'));
        
        // Remove active class from all tab buttons
        const tabButtons = document.querySelectorAll('.tab-btn');
        tabButtons.forEach(btn => btn.classList.remove('active'));
        
        // Show selected tab content
        const selectedContent = document.getElementById(`${tabName}-tab`);
        if (selectedContent) selectedContent.classList.add('active');
        
        // Add active class to selected tab button
        const selectedButton = document.querySelector(`[data-tab="${tabName}"]`);
        if (selectedButton) selectedButton.classList.add('active');
      }
      
      // View management functions
      function changeView(viewType) {
        const gridView = document.getElementById('productsGrid');
        const listView = document.getElementById('productsList');
        const viewButtons = document.querySelectorAll('.view-btn');
        
        // Update button states
        viewButtons.forEach(btn => btn.classList.remove('active'));
        const activeBtn = document.querySelector(`[data-view="${viewType}"]`);
        if (activeBtn) activeBtn.classList.add('active');
        
        // Show/hide views
        if (viewType === 'grid') {
          if (gridView) gridView.style.display = 'grid';
          if (listView) listView.style.display = 'none';
        } else {
          if (gridView) gridView.style.display = 'none';
          if (listView) listView.style.display = 'block';
        }
      }
      
      // Pagination functions
      let currentPage = 1;
      const productsPerPage = 12;
      
      function nextPage() {
        const totalPages = Math.ceil(productManager.getAllProducts().length / productsPerPage);
        if (currentPage < totalPages) {
          currentPage++;
          renderProducts();
          updatePagination();
        }
      }
      
      function previousPage() {
        if (currentPage > 1) {
          currentPage--;
          renderProducts();
          updatePagination();
        }
      }
      
      function updatePagination() {
        const pageNumbers = document.getElementById('pageNumbers');
        if (!pageNumbers) return;
        
        const totalProducts = productManager.getAllProducts().length;
        const totalPages = Math.ceil(totalProducts / productsPerPage);
        
        pageNumbers.innerHTML = '';
        for (let i = 1; i <= totalPages; i++) {
          const pageNumber = document.createElement('span');
          pageNumber.className = `page-number ${i === currentPage ? 'active' : ''}`;
          pageNumber.textContent = i;
          pageNumber.onclick = () => goToPage(i);
          pageNumbers.appendChild(pageNumber);
        }
      }
      
      function goToPage(page) {
        currentPage = page;
        renderProducts();
        updatePagination();
      }
      
      // Search and filter functions
      function searchProducts(query) {
        const searchInput = document.getElementById('searchProducts');
        if (searchInput) searchInput.value = query;
        
        const filteredProducts = productManager.getAllProducts().filter(product =>
          product.name.toLowerCase().includes(query.toLowerCase()) ||
          product.description.toLowerCase().includes(query.toLowerCase()) ||
          product.category.toLowerCase().includes(query.toLowerCase())
        );
        
        renderFilteredProducts(filteredProducts);
      }
      
      function filterByCategory(category) {
        const categoryFilter = document.getElementById('categoryFilter');
        if (categoryFilter) categoryFilter.value = category;
        
        if (!category) {
          renderProducts();
        } else {
          const filteredProducts = productManager.getAllProducts().filter(product => product.category === category);
          renderFilteredProducts(filteredProducts);
        }
      }
      
      function sortProducts(sortType) {
        const sortSelect = document.getElementById('sortProducts');
        if (sortSelect) sortSelect.value = sortType;
        
        let sortedProducts = [...productManager.getAllProducts()];
        
        switch (sortType) {
          case 'newest':
            sortedProducts.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));
            break;
            case 'oldest':
              sortedProducts.sort((a, b) => new Date(a.createdAt) - new Date(b.createdAt));
              break;
              case 'price-low':
                sortedProducts.sort((a, b) => a.price - b.price);
                break;
                case 'price-high':
                  sortedProducts.sort((a, b) => b.price - a.price);
                  break;
                  case 'name-az':
                    sortedProducts.sort((a, b) => a.name.localeCompare(b.name, 'ar'));
                    break;
                    case 'name-za':
                      sortedProducts.sort((a, b) => b.name.localeCompare(a.name, 'ar'));
                      break;
                    }
                    
                    renderFilteredProducts(sortedProducts);
                  }
                  
                  function renderFilteredProducts(products) {
                    const grid = document.getElementById('productsGrid');
                    if (!grid) return;
                    
                    grid.innerHTML = '';
                    products.forEach(product => {
                      const card = createProductCard(product);
                      grid.appendChild(card);
                    });
                  }
                  
                  // Notification System
                  class NotificationManager {
                    constructor() {
                      this.notifications = [];
                      this.container = null;
                      this.init();
                    }
                    
                    init() {
                      // Create notification container
                      this.container = document.createElement('div');
                      this.container.className = 'notification-container';
                      this.container.style.cssText = `
                        position: fixed;
                        top: 20px;
                        right: 20px;
                        z-index: 10000;
                        max-width: 400px;
                        direction: rtl;
                      `;
                      document.body.appendChild(this.container);
                    }
                    
                    show(message, type = 'info', duration = 5000) {
                      const notification = document.createElement('div');
                      notification.className = `notification notification-${type}`;
                      notification.style.cssText = `
                        background: ${this.getTypeColor(type)};
                        color: white;
                        padding: 15px 20px;
                        margin-bottom: 10px;
                        border-radius: 8px;
                        box-shadow: 0 4px 12px rgba(0,0,0,0.15);
                        transform: translateX(100%);
                        transition: transform 0.3s ease;
                        display: flex;
                        align-items: center;
                        gap: 10px;
                        max-width: 100%;
                      `;
                      
                      // Add icon based on type
                      const icon = document.createElement('i');
                      icon.className = this.getTypeIcon(type);
                      notification.appendChild(icon);
                      
                      // Add message
                      const messageText = document.createElement('span');
                      messageText.textContent = message;
                      messageText.style.flex = '1';
                      notification.appendChild(messageText);
                      
                      // Add close button
                      const closeBtn = document.createElement('button');
                      closeBtn.innerHTML = '×';
                      closeBtn.style.cssText = `
                        position: absolute;
                        top: 5px;
                        right: 5px;
                        background: rgba(220, 38, 38, 0.9);
                        color: white;
                        border: none;
                        border-radius: 50%;
                        width: 20px;
                        height: 20px;
                        cursor: pointer;
                        font-size: 14px;
                      `;
                      closeBtn.onclick = () => this.hide(notification);
                      notification.appendChild(closeBtn);
                      
                      // Add to container
                      this.container.appendChild(notification);
                      
                      // Animate in
                      setTimeout(() => {
                        notification.style.transform = 'translateX(0)';
                      }, 100);
                      
                      // Auto-hide after duration
                      if (duration > 0) {
                        setTimeout(() => this.hide(notification), duration);
                      }
                      
                      return notification;
                    }
                    
                    hide(notification) {
                      notification.style.transform = 'translateX(100%)';
                      setTimeout(() => {
                        if (notification.parentNode) {
                          notification.parentNode.removeChild(notification);
                        }
                      }, 300);
                    }
                    
                    getTypeColor(type) {
                      switch (type) {
                        case 'success': return '#16a34a';
                        case 'error': return '#dc2626';
                        case 'warning': return '#ca8a04';
                        case 'info': return '#0891b2';
                        default: return '#64748b';
                      }
                    }
                    
                    getTypeIcon(type) {
                      switch (type) {
                        case 'success': return 'fas fa-check-circle';
                        case 'error': return 'fas fa-exclamation-circle';
                        case 'warning': return 'fas fa-exclamation-triangle';
                        case 'info': return 'fas fa-info-circle';
                        default: return 'fas fa-bell';
                      }
                    }
                  }
                  
                  // Enhanced Event Handlers
                  class EnhancedEventHandlers {
                    constructor() {
                      this.notificationManager = new NotificationManager();
                      this.bindEvents();
                    }
                    
                    bindEvents() {
                      // Form submission with validation
                      const addProductForm = document.getElementById('addProductForm');
                      if (addProductForm) {
                        addProductForm.addEventListener('submit', (e) => this.handleFormSubmit(e));
                      }
                      
                      // Search and filter events
                      const searchInput = document.getElementById('searchProducts');
                      if (searchInput) {
                        searchInput.addEventListener('input', (e) => this.handleSearch(e.target.value));
                      }
                      
                      const categoryFilter = document.getElementById('categoryFilter');
                      if (categoryFilter) {
                        categoryFilter.addEventListener('change', (e) => this.handleCategoryFilter(e.target.value));
                      }
                      
                      const sortSelect = document.getElementById('sortProducts');
                      if (sortSelect) {
                        sortSelect.addEventListener('change', (e) => this.handleSort(e.target.value));
                      }
                      
                      // Image upload handling
                      const imageUploadArea = document.getElementById('imageUploadArea');
                      if (imageUploadArea) {
                        imageUploadArea.addEventListener('click', () => this.handleImageUploadClick());
                        imageUploadArea.addEventListener('dragover', (e) => this.handleDragOver(e));
                        imageUploadArea.addEventListener('drop', (e) => this.handleDrop(e));
                      }
                      
                      // Keyboard shortcuts
                      document.addEventListener('keydown', (e) => this.handleKeyboardShortcuts(e));
                    }
                    
                    handleFormSubmit(e) {
                      e.preventDefault();
                      
                      const formData = new FormData(e.target);
                      const productData = {
                        name: formData.get('productName'),
                        description: formData.get('productDescription'),
                        price: parseFloat(formData.get('productPrice')),
                        category: formData.get('productCategory'),
                        stock: parseInt(formData.get('productStock')) || 0,
                        brand: formData.get('productBrand'),
                        model: formData.get('productModel'),
                        weight: parseFloat(formData.get('productWeight')) || 0,
                        dimensions: formData.get('productDimensions'),
                        features: formData.get('productFeatures')?.split('\n').filter(f => f.trim()) || []
                      };
                      
                      // Validation
                      if (!this.validateProductData(productData)) {
                        return;
                      }
                      
                      // Add product
                      const product = productManager.addProduct(productData);
                      
                      // Show success notification
                      this.notificationManager.show('?? ????? ?????? ?????!', 'success');
                      
                      // Reset form
                      e.target.reset();
                      
                      // Navigate to products view
                      stateManager.navigateTo('products');
                      
                      // Update UI
                      this.updateUIAfterProductChange();
                    }
                    
                    validateProductData(data) {
                      const errors = [];
                      
                      if (!data.name || data.name.trim().length < 2) {
                        errors.push('??? ?????? ??? ?? ???? 3 ???? ??? ?????');
                      }
                      
                      if (!data.description || data.description.trim().length < 10) {
                        errors.push('??? ?????? ??? ?? ???? 10 ???? ??? ?????');
                      }
                      
                      if (!data.price || data.price <= 0) {
                        errors.push('????? ??? ?? ???? ???? ?? ???');
                      }
                      
                      if (!data.category) {
                        errors.push('??? ?????? ??? ??????');
                      }
                      
                      if (errors.length > 0) {
                        errors.forEach(error => {
                          this.notificationManager.show(error, 'error');
                        });
                        return false;
                      }
                      
                      return true;
                    }
                    
                    handleSearch(query) {
                      if (query.length >= 2 || query.length === 0) {
                        stateManager.setFilter('search', query);
                      }
                    }
                    
                    handleCategoryFilter(category) {
                      stateManager.setFilter('category', category);
                    }
                    
                    handleSort(sortType) {
                      stateManager.setFilter('sortBy', sortType);
                    }
                    
                    handleImageUploadClick() {
                      const fileInput = document.getElementById('productImages');
                      if (fileInput) {
                        fileInput.click();
                      }
                    }
                    
                    handleDragOver(e) {
                      e.preventDefault();
                      e.currentTarget.style.borderColor = '#2563eb';
                      e.currentTarget.style.background = '#eff6ff';
                    }
                    
                    handleDrop(e) {
                      e.preventDefault();
                      e.currentTarget.style.borderColor = '#e2e8f0';
                      e.currentTarget.style.background = 'white';
                      
                      const files = Array.from(e.dataTransfer.files);
                      this.processImageFiles(files);
                    }
                    
                    processImageFiles(files) {
                      const imageFiles = files.filter(file => file.type.startsWith('image/'));
                      
                      if (imageFiles.length === 0) {
                        this.notificationManager.show('???? ?????? ????? ??? ?????', 'warning');
                        return;
                      }
                      
                      // Process and preview images
                      imageFiles.forEach(file => {
                        const reader = new FileReader();
                        reader.onload = (e) => this.addImagePreview(e.target.result, file.name);
                        reader.readAsDataURL(file);
                      });
                      
                      this.notificationManager.show(`?? ????? ${imageFiles.length} ????`, 'success');
                    }
                    
                    addImagePreview(src, name) {
                      const previewContainer = document.getElementById('imagePreview');
                      if (!previewContainer) return;
                      
                      const previewItem = document.createElement('div');
                      previewItem.className = 'image-preview-item';
                      previewItem.style.cssText = `
                        position: relative;
                        width: 100px;
                        height: 100px;
                        border-radius: 8px;
                        overflow: hidden;
                        border: 2px solid #e2e8f0;
                      `;
                      
                      const img = document.createElement('img');
                      img.src = src;
                      img.style.cssText = 'width: 100%; height: 100%; object-fit: cover;';
                      previewItem.appendChild(img);
                      
                      const removeBtn = document.createElement('button');
                      removeBtn.innerHTML = '×';
                      removeBtn.style.cssText = `
                        position: absolute;
                        top: 5px;
                        right: 5px;
                        background: rgba(220, 38, 38, 0.9);
                        color: white;
                        border: none;
                        border-radius: 50%;
                        width: 20px;
                        height: 20px;
                        cursor: pointer;
                        font-size: 14px;
                      `;
                      removeBtn.onclick = () => previewItem.remove();
                      previewItem.appendChild(removeBtn);
                      
                      previewContainer.appendChild(previewItem);
                    }
                    
                    handleKeyboardShortcuts(e) {
                      // Ctrl/Cmd + K for search
                      if ((e.ctrlKey || e.metaKey) && e.key === 'k') {
                        e.preventDefault();
                        const searchInput = document.getElementById('searchProducts');
                        if (searchInput) searchInput.focus();
                      }
                      
                      // Ctrl/Cmd + N for new product
                      if ((e.ctrlKey || e.metaKey) && e.key === 'n') {
                        e.preventDefault();
                        stateManager.navigateTo('add-product');
                      }
                      
                      // Escape to close modals/forms
                      if (e.key === 'Escape') {
                        this.closeAllModals();
                      }
                    }
                    
                    closeAllModals() {
                      // Close any open modals or forms
                      const modals = document.querySelectorAll('.modal, .form-overlay');
                      modals.forEach(modal => {
                        modal.style.display = 'none';
                      });
                    }
                    
                    updateUIAfterProductChange() {
                      // Update product count
                      const productCount = document.getElementById('productCount');
                      if (productCount) {
                        productCount.textContent = productManager.getAllProducts().length;
                      }
                      
                      // Refresh products display
                      if (stateManager.getState('navigation').currentSection === 'products') {
                        renderProducts();
                      }
                    }
                  }
                  
                  // Initialize enhanced event handlers
                  const enhancedEventHandlers = new EnhancedEventHandlers();
                  
                  // Make functions globally available
                  window.ProductOperations = ProductOperations;
                  window.EventHandlers = EventHandlers;
                  window.Utils = Utils;
                  window.productManager = productManager;
                  window.stateManager = stateManager;
                  window.switchTab = switchTab;
                  window.changeView = changeView;
                  window.nextPage = nextPage;
                  window.previousPage = previousPage;
                  window.searchProducts = searchProducts;
                  window.filterByCategory = filterByCategory;
                  window.sortProducts = sortProducts;
                  
                })();
