import java.io.FileWriter;
import java.io.IOException;

public class SimpleCodeGenTest {
    
    public static void main(String[] args) {
        System.out.println("=== Angular Compiler with Code Generation ===");
        
        // Simulate parsing an Angular component and generating code
        generateHTMLCode();
        generateCSSCode();
        generateJSCode();
        
        System.out.println("\nCode generation complete! Check the generated files:");
        System.out.println("- generated_app.html");
        System.out.println("- generated_app.css");
        System.out.println("- generated_app.js");
    }
    
    private static void generateHTMLCode() {
        String htmlCode = generateSampleHTML();
        saveToFile("generated_app.html", htmlCode);
        System.out.println("Generated HTML code");
    }
    
    private static void generateCSSCode() {
        String cssCode = generateSampleCSS();
        saveToFile("generated_app.css", cssCode);
        System.out.println("Generated CSS code");
    }
    
    private static void generateJSCode() {
        String jsCode = generateSampleJS();
        saveToFile("generated_app.js", jsCode);
        System.out.println("Generated JavaScript code");
    }
    
    private static String generateSampleHTML() {
        StringBuilder html = new StringBuilder();
        html.append("<!DOCTYPE html>\n");
        html.append("<html lang=\"en\">\n");
        html.append("<head>\n");
        html.append("    <meta charset=\"UTF-8\">\n");
        html.append("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
        html.append("    <title>Generated Angular Products App</title>\n");
        html.append("    <link rel=\"stylesheet\" href=\"generated_app.css\">\n");
        html.append("</head>\n");
        html.append("<body>\n");
        html.append("    <div class=\"products-container\">\n");
        html.append("        <h1>Product Catalog</h1>\n");
        html.append("        \n");
        html.append("        <div class=\"filters\">\n");
        html.append("            <input type=\"text\" id=\"searchTerm\" placeholder=\"Search products...\">\n");
        html.append("            <select id=\"selectedCategory\">\n");
        html.append("                <option value=\"\">All Categories</option>\n");
        html.append("                <option value=\"electronics\">Electronics</option>\n");
        html.append("                <option value=\"clothing\">Clothing</option>\n");
        html.append("                <option value=\"books\">Books</option>\n");
        html.append("            </select>\n");
        html.append("        </div>\n");
        html.append("        \n");
        html.append("        <div class=\"product-grid\" id=\"productGrid\">\n");
        html.append("            <!-- Products will be generated by JavaScript -->\n");
        html.append("        </div>\n");
        html.append("        \n");
        html.append("        <div id=\"noProducts\" class=\"no-products\" style=\"display: none;\">\n");
        html.append("            No products found matching your criteria.\n");
        html.append("        </div>\n");
        html.append("        \n");
        html.append("        <div class=\"cart-summary\">\n");
        html.append("            <h3>Cart Summary</h3>\n");
        html.append("            <p>Items in cart: <span id=\"cartCount\">0</span></p>\n");
        html.append("            <p>Total: $<span id=\"cartTotal\">0.00</span></p>\n");
        html.append("        </div>\n");
        html.append("    </div>\n");
        html.append("    \n");
        html.append("    <script src=\"generated_app.js\"></script>\n");
        html.append("</body>\n");
        html.append("</html>\n");
        return html.toString();
    }
    
    private static String generateSampleCSS() {
        StringBuilder css = new StringBuilder();
        css.append("/* Generated CSS from Angular Components */\n\n");
        css.append("* {\n");
        css.append("    box-sizing: border-box;\n");
        css.append("    margin: 0;\n");
        css.append("    padding: 0;\n");
        css.append("}\n\n");
        css.append("body {\n");
        css.append("    font-family: Arial, sans-serif;\n");
        css.append("    line-height: 1.6;\n");
        css.append("    color: #333;\n");
        css.append("    background-color: #f5f5f5;\n");
        css.append("}\n\n");
        css.append(".products-container {\n");
        css.append("    max-width: 1200px;\n");
        css.append("    margin: 0 auto;\n");
        css.append("    padding: 20px;\n");
        css.append("    background: white;\n");
        css.append("    border-radius: 8px;\n");
        css.append("    box-shadow: 0 2px 10px rgba(0,0,0,0.1);\n");
        css.append("}\n\n");
        css.append(".filters {\n");
        css.append("    display: flex;\n");
        css.append("    gap: 15px;\n");
        css.append("    margin-bottom: 30px;\n");
        css.append("}\n\n");
        css.append(".filters input, .filters select {\n");
        css.append("    padding: 10px;\n");
        css.append("    border: 1px solid #ddd;\n");
        css.append("    border-radius: 5px;\n");
        css.append("    font-size: 16px;\n");
        css.append("}\n\n");
        css.append(".product-grid {\n");
        css.append("    display: grid;\n");
        css.append("    grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));\n");
        css.append("    gap: 20px;\n");
        css.append("    margin-bottom: 30px;\n");
        css.append("}\n\n");
        css.append(".product-card {\n");
        css.append("    border: 1px solid #ddd;\n");
        css.append("    border-radius: 8px;\n");
        css.append("    padding: 15px;\n");
        css.append("    background: white;\n");
        css.append("    box-shadow: 0 2px 4px rgba(0,0,0,0.1);\n");
        css.append("    transition: transform 0.2s;\n");
        css.append("}\n\n");
        css.append(".product-card:hover {\n");
        css.append("    transform: translateY(-2px);\n");
        css.append("    box-shadow: 0 4px 8px rgba(0,0,0,0.15);\n");
        css.append("}\n\n");
        css.append(".product-card h3 {\n");
        css.append("    margin: 0 0 10px 0;\n");
        css.append("    color: #333;\n");
        css.append("}\n\n");
        css.append(".product-card .description {\n");
        css.append("    color: #666;\n");
        css.append("    margin-bottom: 10px;\n");
        css.append("    line-height: 1.4;\n");
        css.append("}\n\n");
        css.append(".product-card .price {\n");
        css.append("    font-size: 18px;\n");
        css.append("    font-weight: bold;\n");
        css.append("    color: #007bff;\n");
        css.append("    margin-bottom: 10px;\n");
        css.append("}\n\n");
        css.append(".product-card button {\n");
        css.append("    background: #007bff;\n");
        css.append("    color: white;\n");
        css.append("    border: none;\n");
        css.append("    padding: 10px 15px;\n");
        css.append("    border-radius: 5px;\n");
        css.append("    cursor: pointer;\n");
        css.append("    font-size: 14px;\n");
        css.append("    transition: background 0.2s;\n");
        css.append("}\n\n");
        css.append(".product-card button:hover {\n");
        css.append("    background: #0056b3;\n");
        css.append("}\n\n");
        css.append(".no-products {\n");
        css.append("    text-align: center;\n");
        css.append("    padding: 40px;\n");
        css.append("    color: #666;\n");
        css.append("    font-size: 18px;\n");
        css.append("}\n\n");
        css.append(".cart-summary {\n");
        css.append("    background: #f8f9fa;\n");
        css.append("    padding: 20px;\n");
        css.append("    border-radius: 8px;\n");
        css.append("    border: 1px solid #ddd;\n");
        css.append("}\n\n");
        css.append(".cart-summary h3 {\n");
        css.append("    margin-top: 0;\n");
        css.append("    color: #333;\n");
        css.append("}\n");
        return css.toString();
    }
    
    private static String generateSampleJS() {
        StringBuilder js = new StringBuilder();
        js.append("// Generated JavaScript from Angular Components\n");
        js.append("'use strict';\n\n");
        js.append("// Application namespace\n");
        js.append("const App = {};\n\n");
        js.append("// Products Component\n");
        js.append("App.ProductsComponent = {\n");
        js.append("    searchTerm: '',\n");
        js.append("    selectedCategory: '',\n");
        js.append("    cartItems: [],\n");
        js.append("    \n");
        js.append("    products: [\n");
        js.append("        {\n");
        js.append("            id: 1,\n");
        js.append("            name: 'Wireless Headphones',\n");
        js.append("            price: 99.99,\n");
        js.append("            description: 'High-quality wireless headphones with noise cancellation',\n");
        js.append("            category: 'electronics',\n");
        js.append("            inStock: true\n");
        js.append("        },\n");
        js.append("        {\n");
        js.append("            id: 2,\n");
        js.append("            name: 'Cotton T-Shirt',\n");
        js.append("            price: 24.99,\n");
        js.append("            description: 'Comfortable 100% cotton t-shirt in various colors',\n");
        js.append("            category: 'clothing',\n");
        js.append("            inStock: true\n");
        js.append("        },\n");
        js.append("        {\n");
        js.append("            id: 3,\n");
        js.append("            name: 'JavaScript Guide',\n");
        js.append("            price: 39.99,\n");
        js.append("            description: 'Complete guide to modern JavaScript development',\n");
        js.append("            category: 'books',\n");
        js.append("            inStock: false\n");
        js.append("        }\n");
        js.append("    ],\n");
        js.append("    \n");
        js.append("    init: function() {\n");
        js.append("        this.render();\n");
        js.append("        this.bindEvents();\n");
        js.append("    },\n");
        js.append("    \n");
        js.append("    render: function() {\n");
        js.append("        const productGrid = document.getElementById('productGrid');\n");
        js.append("        const filteredProducts = this.getFilteredProducts();\n");
        js.append("        \n");
        js.append("        productGrid.innerHTML = '';\n");
        js.append("        \n");
        js.append("        filteredProducts.forEach(product => {\n");
        js.append("            const productCard = this.createProductCard(product);\n");
        js.append("            productGrid.appendChild(productCard);\n");
        js.append("        });\n");
        js.append("        \n");
        js.append("        document.getElementById('noProducts').style.display = \n");
        js.append("            filteredProducts.length === 0 ? 'block' : 'none';\n");
        js.append("        \n");
        js.append("        this.updateCartSummary();\n");
        js.append("    },\n");
        js.append("    \n");
        js.append("    createProductCard: function(product) {\n");
        js.append("        const card = document.createElement('div');\n");
        js.append("        card.className = 'product-card';\n");
        js.append("        \n");
        js.append("        card.innerHTML = `\n");
        js.append("            <h3>${product.name}</h3>\n");
        js.append("            <p class=\"description\">${product.description}</p>\n");
        js.append("            <div class=\"price\">$${product.price}</div>\n");
        js.append("            <button onclick=\"App.ProductsComponent.addToCart(${product.id})\" \n");
        js.append("                    ${!product.inStock ? 'disabled' : ''}>\n");
        js.append("                ${product.inStock ? 'Add to Cart' : 'Out of Stock'}\n");
        js.append("            </button>\n");
        js.append("        `;\n");
        js.append("        \n");
        js.append("        return card;\n");
        js.append("    },\n");
        js.append("    \n");
        js.append("    getFilteredProducts: function() {\n");
        js.append("        return this.products.filter(product => {\n");
        js.append("            const matchesSearch = product.name.toLowerCase().includes(this.searchTerm.toLowerCase()) ||\n");
        js.append("                                 product.description.toLowerCase().includes(this.searchTerm.toLowerCase());\n");
        js.append("            const matchesCategory = !this.selectedCategory || product.category === this.selectedCategory;\n");
        js.append("            return matchesSearch && matchesCategory;\n");
        js.append("        });\n");
        js.append("    },\n");
        js.append("    \n");
        js.append("    addToCart: function(productId) {\n");
        js.append("        const product = this.products.find(p => p.id === productId);\n");
        js.append("        if (product && product.inStock) {\n");
        js.append("            this.cartItems.push(product);\n");
        js.append("            this.updateCartSummary();\n");
        js.append("            console.log(`Added ${product.name} to cart`);\n");
        js.append("        }\n");
        js.append("    },\n");
        js.append("    \n");
        js.append("    updateCartSummary: function() {\n");
        js.append("        document.getElementById('cartCount').textContent = this.cartItems.length;\n");
        js.append("        const total = this.cartItems.reduce((sum, item) => sum + item.price, 0);\n");
        js.append("        document.getElementById('cartTotal').textContent = total.toFixed(2);\n");
        js.append("    },\n");
        js.append("    \n");
        js.append("    bindEvents: function() {\n");
        js.append("        const searchInput = document.getElementById('searchTerm');\n");
        js.append("        const categorySelect = document.getElementById('selectedCategory');\n");
        js.append("        \n");
        js.append("        searchInput.addEventListener('input', (e) => {\n");
        js.append("            this.searchTerm = e.target.value;\n");
        js.append("            this.render();\n");
        js.append("        });\n");
        js.append("        \n");
        js.append("        categorySelect.addEventListener('change', (e) => {\n");
        js.append("            this.selectedCategory = e.target.value;\n");
        js.append("            this.render();\n");
        js.append("        });\n");
        js.append("    }\n");
        js.append("};\n");
        js.append("\n");
        js.append("// Initialize application\n");
        js.append("document.addEventListener('DOMContentLoaded', function() {\n");
        js.append("    App.ProductsComponent.init();\n");
        js.append("});\n");
        return js.toString();
    }
    
    private static void saveToFile(String filename, String content) {
        try (FileWriter writer = new FileWriter(filename)) {
            writer.write(content);
        } catch (IOException e) {
            System.err.println("Error saving file " + filename + ": " + e.getMessage());
        }
    }
}

